### ISSUE TITLE
rlas 1.3.6 indirect backward incompatibility

### ISSUE THREAD

**Issue by Jean-Romain** [tiagodc/TreeLS#11]
Hi Tiago,

I recently released `rlas` 1.3.6 in which I added stronger standard specification validity tests. While backward compatibility has been tested your package actually depends on `rlas` indirectly via `lidR` and was not tested.

You now have errors on CRAN because your LAS files contain NAs in standard attributes such as gpstime which is not allowed. I don't know how you managed to write readable NAs in gpstime but this must be fixed.

```r
file = system.file("extdata", "model_boles.laz", package="TreeLS")
tls = readTLS(file)
#> Erreur : Invalid data: gpstime contains some NAs
```

Cheers.

**Comment by tiagodc** [comment]
Hi Jean,

I haven't worked on TreeLS for quite some time and I am slowly retaking the work. Among other things, I have to re-check the lidR dependencies and change my code accordingly, so I will revise the whole package again as soon as I get a deeper dive on the latest lidR release.

Thanks for the heads up!
