### ISSUE TITLE
‘TreeLS’ is not available (for R version XYZ)

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [tiagodc/TreeLS#13]
I have been trying to install this package since a long time now and I keep getting this error:
`Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘TreeLS’ is not available (for R version 4.0.2)`

Also, the package has been [removed](https://cran.r-project.org/web/packages/TreeLS/index.html) from CRAN.
I am all trying to get install it using `devtools::install_github('tiagodc/TreeLS', ref='old')` but no luck.

How can I use this package in R now?

**Comment by amygresham** [comment]
You can install the package to an older version of R by changing the version of R you are using in the global options.

**Comment by Jean-Romain** [comment]
> but no luck.

What does it mean? What is the error message?

**Comment by mansi-aggarwal-2504** [comment]
> You can install the package to an older version of R by changing the version of R you are using in the global options.

@amygresham I tried to install it to older versions also. It didn't work. I get the same error: `Warning in install.packages : package ‘TreeLS’ is not available (for R version 3.6.2)`

> What does it mean? What is the error message?

@Jean-Romain I get an error like this: `installation of package had non-zero exit status`

I managed when I copied the library from the lib path of a system I was using TreeLS on, and pasted the folder to the new VM and it worked somehow. But this is a workaround. I want to know what the reason for this problem is, if anyone could tell.

**Comment by Jean-Romain** [comment]
> installation of package had non-zero exit status

This is not the error. This is only the "conclusion". You have an error displayed somewhere in the output of the installation

**Comment by mansi-aggarwal-2504** [comment]
@Jean-Romain I was somehow able to reproduce the error. Please let me know if this helps:

`Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rgl/libs/rgl.so
  Reason: image not found
Error: .onLoad failed in loadNamespace() for 'rgl', details:
  call: NULL
  error: 	Loading rgl's DLL failed. 
	On MacOS, rgl depends on XQuartz, which you can download from xquartz.org.
Execution halted
ERROR: lazy loading failed for package ‘TreeLS’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/TreeLS’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/TreeLS’
Error: Failed to install 'TreeLS' from GitHub:
  (converted from warning) installation of package ‘/var/folders/vp/s7zhrkrd3x954qk3xw00krxc0000gn/T//Rtmp7WKwiW/file302a1db54e59/TreeLS_1.0.1.tar.gz’ had non-zero exit status`

**Comment by Jean-Romain** [comment]
Never seen that. It seems that your installation of `rgl` is incorrect and it seems to be a MacOS specific issue.

**Comment by amygresham** [comment]
I have been having the same issue. I am only able to access TreeLS on an earlier version of R because I installed it before it was removed from CRAN. As far as I can see, the package is no longer available for download. 

If you google the CRAN documentation for TreeLS this text appears:

**"Package ‘TreeLS’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2020-07-05 as check issues were not corrected in time.

Please use the canonical form https://CRAN.R-project.org/package=TreeLS to link to this page."**

**Comment by stefanoch90** [comment]
Hello, I have the same problem too, it says so: Warning in install.packages : package ‘TreeLS’ is not available (for R version 4.0.2). How can i solve this issue?
I have installed it in Windows 10.

**Comment by Jean-Romain** [comment]
The package is no longer on CRAN for the moment. There is nothing to "fix". You can install it from the source.

**Comment by stefanoch90** [comment]
Thank you for the quick reply. Can you advise me what procedure to do to install from the source?

**Comment by Jean-Romain** [comment]
https://stackoverflow.com/questions/1474081/how-do-i-install-an-r-package-from-source

**Comment by stefanoch90** [comment]
Thank you very much. My best regards.

**Comment by Jean-Romain** [comment]
Have you read the [README](https://github.com/tiagodc/TreeLS)?

**Comment by stefanoch90** [comment]
I have followed this flow:
Requirements
devtools: run install.packages('devtools', dependencies = TRUE) from the R console 
Rcpp compiler:
on Windows: install Rtools for your R version - make sure to add it to your system's path.
But i don't find any packages TreeLS.

I thank you for your kindness.

**Comment by mansi-aggarwal-2504** [comment]
> Hi, i have followed your suggests and now i can processing my .LAS file with the TreeLs library.
> I thank you for your kindness.

Hello, @stefanoch90, could you tell what worked for you? Did you check the archive file from CRAN page? **Formerly available versions can be obtained from the archive.** and installed library from source?

**Comment by stefanoch90** [comment]
Hello @mansi-aggarwal-2504 , i have followed the following list:
- devtools: run install.packages('devtools', dependencies = TRUE) from the R console;
- Rcpp compiler:
on Windows: install Rtools for your R version - make sure to add it to your system's path (because i have got Windows 10);
- devtools::install_github('tiagodc/TreeLS')
- library(TreeLS).
I made in this way and now i can work in an efficiently way.

**Comment by tiagodc** [comment]
Hi there, TreeLS is out of CRAN at the moment indeed, I already reviewed and fixed all dependency issues, most of the documentation and have a few tweaks and tests to do, but I intend to release a new version still this month. Sorry about the inconveniences and thanks @Jean-Romain for helping out!
