### ISSUE TITLE
export data from 

### ISSUE THREAD

**Issue by stefanoch90** [tiagodc/TreeLS#14]
Hi , i have a question: how can I export the data after the    "# extract measures"? because i would like for each single  stem its ID number and the measurement of the diameter of each segment for each height.
I hope I made myself as clear as possible with the request.

**Comment by bi0m3trics** [comment]
The help for `stemSegmentation` says that it returns a "data.table of stem segments with stem_dt signature." so the solution would be the same way you export any other data.frame/data.table...
e.g., write.csv(seg, "path to file")

**Comment by tiagodc** [comment]
Thanks @bi0m3trics , that's exactly right. Also, if you want to export the fields added to your LAS files you can refer to `lidR::add_lasattribute`.

**Comment by stefanoch90** [comment]
Thank you very much.
You are very kindly.

Stefano

Il giorno mer 22 lug 2020 alle ore 15:57 Tiago de Conto <
notifications@github.com> ha scritto:
