### ISSUE TITLE
tlsNormalize

### ISSUE THREAD

**Issue by stefanoch90** [tiagodc/TreeLS#15]
Hi, i have a problema con il command "tlsNormalize". 
I import the .LAS file from CLoudcompare after to apply the CSF plugin. The cloud import in R is only DSM. When i launch the tlsNormalize command, the score is " no ground points found, performing ground segmentation".
How can i resolve this problem?

**Comment by stefanoch90** [comment]
I have solved my question, the problem is the type file selected in cloudCompare. It is necessary save file in LAS 1.3 or 1.4 .

**Comment by bi0m3trics** [comment]
In case you didn't know, the lidR package has an implementation of CSF in lidR::classify_ground(). This will allow you to keep your workflow entirely within R..

https://jean-romain.github.io/lidRbook/gnd.html#csf

**Comment by stefanoch90** [comment]
Can CSF of lidR supports the point cloud any milion points?

**Comment by Jean-Romain** [comment]
The CSF of lidR relies on the same source code that the one of cloud compare i.e. the source code of the authors themselves.

**Comment by stefanoch90** [comment]
Yes, thank you very much for more details that you have provided me.

**Comment by stefanoch90** [comment]
I have another question: do you know a package or workflow to detection the Crown Base Height for each tree? thank you
