### ISSUE TITLE
Error on installing devel version

### ISSUE THREAD

**Issue by jdonager** [tiagodc/TreeLS#17]
Hi, and thanks for writing this awesome package. 
I have been trying to install the development version and have gotten the same error on multiple machines, both windows and linux:

methods.cpp:932:5: error: 'progressPrinter' was not declared in this scope
     progressPrinter("trees", i, trees.size());
     ^~~~~~~~~~~~~~~
make: *** [C:/PROGRA~1/R/R-40~1.2/etc/i386/Makeconf:229: methods.o] Error 1
ERROR: compilation failed for package 'TreeLS'
* removing 'C:/Users/jonat/Documents/R/win-library/4.0/TreeLS'
* restoring previous 'C:/Users/jonat/Documents/R/win-library/4.0/TreeLS'
Error: Failed to install 'TreeLS' from GitHub:
  (converted from warning) installation of package ‘C:/Users/jonat/AppData/Local/Temp/Rtmp4iN5ec/file47ce5b4a1f/TreeLS_2.0.0.tar.gz’ had non-zero exit status

Just wanted to bring it to your attention. It seems like an error stemming from a missing c function.
Thanks again, 
Jonathon Donager

**Comment by tiagodc** [comment]
Hi there, thanks for pointing it out. I just replaced the C++ header files in the inst directory. Now it should work. Cheers!
