### ISSUE TITLE
treePoints saying crs does not match, treeMap removes crs

### ISSUE THREAD

**Issue by jdonager** [tiagodc/TreeLS#18]
Hi again, 
I am trying to use the treePoints function in conjunction with treeMap(). When I run treeMap, the las object that is returned has no CRS argument. So when I use it within the treePoints function, it gives an error:
Error in .local(x, y, returnList, fn, ...) : 
  identicalCRS(x, y) is not TRUE
If I set the CRS argument of the map object to that of the las object so that they do in fact match, I get the same error. Interestingly, las objects without a CRS argument do not see this error and I cannot figure out how to remove the CRS argument from the las object. 
If needed, I can provide the las object.
Thanks.

**Comment by Jean-Romain** [comment]
Please show a minimal reproducible example of code.

**Comment by jdonager** [comment]
>   crs(las)
CRS arguments:
 +proj=utm +zone=12 +datum=WGS84 +units=m +no_defs 
>   map <- treeMap(las)
>   crs(map)
CRS arguments: NA 
>   trees <-treePoints(las, map, method = trp.voronoi())
Error in .local(x, y, returnList, fn, ...) : 
  identicalCRS(x, y) is not TRUE
>   crs(map) <- crs(las)
>   crs(map)
CRS arguments:
 +proj=utm +zone=12 +datum=WGS84 +units=m +no_defs 
>   trees <-treePoints(las, map, method = trp.voronoi())
Error in .local(x, y, returnList, fn, ...) : 
  identicalCRS(x, y) is not TRUE

**Comment by jdonager** [comment]
a link to the .laz file:
https://drive.google.com/file/d/1Rh_Jif47J01luUzfyZbXffn1VUwIipzx/view?usp=sharing

**Comment by jdonager** [comment]
las <- readLAS(location)
crs(las)
map <- treeMap(las)
crs(map)
trees <-treePoints(las, map, method = trp.voronoi())
crs(map) <- crs(las)
crs(map)
trees <-treePoints(las, map, method = trp.voronoi())

**Comment by Jean-Romain** [comment]
Seems that internal code drops the CRS somewhere. Definitively looks like a bug. I can't see where but it does seems to be related to `lidR` so I let @tiagodc investigate.

**Comment by jdonager** [comment]
Great! Thanks for the incredibly prompt replies.

**Comment by tiagodc** [comment]
Just fixed. Indeed it was a bug in `trp.voronoi`. Thanks for pointing it out! You can reinstall the package from source now and it should work.

**Comment by jdonager** [comment]
Such a fast fix! Thanks, you guys are awesome.
