### ISSUE TITLE
TreeLS is no avaible on CRAN

### ISSUE THREAD

**Issue by stefanoch90** [tiagodc/TreeLS#19]
Hi, the TreeLS package is not available on CRAN and R official library. How do i make to download the new version 2.0?
thank you.

**Comment by jdonager** [comment]
devtools::install_github("tiagodc/TreeLS", ref="devel")

**Comment by Jean-Romain** [comment]
The lastest version is in `master`

```r
remotes::install_github("tiagodc/TreeLS")
```

**Comment by tiagodc** [comment]
You can download it from `master` as @Jean-Romain pointed out. I already passed through a couple reviews from CRAN, but it is on vacation until the 24th. As soon as it gets back online I'll resubmit, so the package should be available within the next couple weeks in CRAN as well.
