### ISSUE TITLE
Error in read.dcf(path)  when installing

### ISSUE THREAD

**Issue by bimtauer** [tiagodc/TreeLS#2]
Hi there, 
thanks for creating this package - I believe it could help me a lot right now. 
Unfortunately when I try installing with devtools::install_github('tiagodc/TreeLS') it throws the following error: 
```
Error in read.dcf(path) : 
  Found continuation line starting '    terrestrial lase ...' at begin of record.
```

**Comment by tiagodc** [comment]
hi there, thanks for using this package! I've fixed the bug, the installation should work fine by now.
I haven't touched the package in about two years, but I have plans for it in 2019.
I'll put some comments on that later on at the `README ` file.
