### ISSUE TITLE
TreeLS installation error (macOS)

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [tiagodc/TreeLS#21]
I am using R 4.0.2 (upgraded from 3.6.2 due to a certain error while installing data.table)
I am trying to install TreeLS using `devtools::install_github('tiagodc/TreeLS')` but I am getting this error. 

<img width="872" alt="Screenshot 2020-08-24 at 11 32 23 AM" src="https://user-images.githubusercontent.com/60866597/91010477-344be900-e600-11ea-9a8f-3a376136f81a.png">

I think that the problem lies in the link between R and clang. Does anyone know how I can fix this issue?

**EDIT:**

I followed steps mentioned [here, on Rstudio community mentioning a similar problem](https://community.rstudio.com/t/r-4-0-2-mac-issue-when-installing-packages-from-source/71875) and followed the [solution mentioned](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/). I downloaded and installed the appropriate `gfortran` binary. But I'm getting a different error now:

<img width="872" alt="Screenshot 2020-08-24 at 11 32 23 AM" src="https://user-images.githubusercontent.com/60866597/91025723-63218980-e617-11ea-816b-0e287936ce21.png">

Seems like I need something called XQuartz. Is there a workaround or is it necessary for all macOS users?

**Comment by tiagodc** [comment]
XQuartz is used for 3D plotting with `rgl` on macOS, check [this](https://stackoverflow.com/questions/9878693/error-in-loading-rgl-package-with-mac-os-x) thread as it might be helpful.

Unfortunately I don't have access to a macOS right now to debug, so if anyone can help I appreciate!

**Comment by tiagodc** [comment]
@mansi-aggarwal-2504 , did you manage to solve this issue? Can I close this?
