### ISSUE TITLE
no ground points, performing segmentation

### ISSUE THREAD

**Issue by tasimuumbe** [tiagodc/TreeLS#25]
I am new to TreeLS and I am following the tutorial to process a TLS point cloud. When normalizing the point cloud, I am getting a warning message "no ground points, performing segmentation".

**Comment by tiagodc** [comment]
It's not a warning, just a message to the user. When the input point cloud doesn't have any ground classification, `tlsNormalize` does it internally, it's even described the function's help page. The message serves as an "alert", as the user has no control over the ground filter algorithm or parameters used internally, so they might prefer to go back and do it with some fine tuning on the algorithm - check out `lidR::classify_ground` if you want more information on ground classification methods.
