### ISSUE TITLE
treeMap.merge - Not working

### ISSUE THREAD

**Issue by sweco-sekrsv** [tiagodc/TreeLS#30]
I can't get the treeMap.merge to work as I expect. 
I'm using these values:

```
map = treeMap(tls, map.hough(h_step = 1, max_h = 6, min_h = 5),merge = 1.0)
xymap = treeMap.positions(map, plot = FALSE)
add_treeMap(x, xymap, color='yellow')
```

I was thinking that with a merge value of 1 all treeMap.positions within a meter distance would merge to one. But I don't see any points being merged at all, even when setting the merge to very high values like 100. 

Maybe I misunderstood what it does? This image shows the result:
![stamsegmentering_TreeLS_02](https://user-images.githubusercontent.com/10772529/95990158-72f56700-0e2b-11eb-930f-3988e0db79b8.png)

**Comment by tiagodc** [comment]
Thanks for the comment, 

that _merge_ function is not so straight forward, I'll consider writing a better description for it. Right now it is:

> _The d parameter is a relative measure of close neighbors. Sorting all possible pairs by distance from a tree map, the merge criterion is that none of the closest pairs should be distant less than the next closest pair's distance minus d. This method is useful when merging forked stems or point clusters from plots with too much understory, especially if those are from forest stands with regularly spaced trees._ 

This method is particularly useful for clouds of regularly spaced trees in forest plantations. The `d` parameter is a ratio, and the _lower_ it is, the more inclusive the merging is, i.e. more trees will be merged the lower _d_ is.

I'll consider adding another simpler _merge_  function on next version, with straightforward distance inputs. In the meantime, you can try to filter out or merge the trees from your map with a custom method using a distance matrix as criteria. This snippet gets the distance from every tree in a map to its nearest neighbor:

```
map = treeMap(las, positions_only=T)
map$d_nn = map[,.(X,Y)] %>% dist %>% as.matrix %>% as.data.table %>% sapply(function(x) sort(x)[2])
```

Cheers
