### ISSUE TITLE
algorithms

### ISSUE THREAD

**Issue by spono** [tiagodc/TreeLS#4]
Hi!
first of all: many thanks for the great work!
I think that such a package can open up huge opportunities for this field of study...and the integration with lidR is a big plus!
As you wrote on the main page "Suggestions are welcome". Well, here some food for thoughts:
- [Hackenberg](https://www.mdpi.com/1999-4907/5/5/1069),
- [Bucksch](https://link.springer.com/article/10.1007/s00371-010-0520-4)
- [Polewski](https://www.sciencedirect.com/science/article/pii/S0924271617301211?via%3Dihub)
- [Putman](https://ieeexplore.ieee.org/document/8401534)

BTW, I'll play around with this package quite a while!
all the best

**Comment by tiagodc** [comment]
Thanks! Appreciated!

Hackenberg's work is on my top shelf for quite some time already. As for the other ones, I'm sure some implementations are also worth exploring.

I'm late on my own schedule here, but I already have several other methods implemented for stem points classification and segmentation, based on Liang's and Raumonen's work, as well as some new tools. I just need to wrap the C++ into R again and republish... I'm hoping I can submit a new version within the next couple weeks.

Thanks again for sharing and keep exploring :)
