### ISSUE TITLE
Installation of version 2.0.2

### ISSUE THREAD

**Issue by karasinski88** [tiagodc/TreeLS#47]
Hi, @tiagodc 

I'm trying to install the new version of TreeLS, but I'm not succeeding.

The fact that TreeLS is not available on CRAN, I was only able to install the old version of the program. but I can't find the functions I need in the old version

for this I used the following command:

```
install.packages('devtools', dependencies = TRUE)
devtools::install_github('tiagodc/TreeLS')

```

generates an error:

```
Erro: Failed to install 'TreeLS' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
E>   namespace 'glue' 1.3.1 is already loaded, but >= 1.3.2 is required
E> Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
E> Execução interrompida
E> ERROR: lazy loading failed for package 'TreeLS'
E> * removing 'C:/Users/Avell/AppData/Local/Temp/RtmpGkIAKn/Rinst33246a752bb6/TreeLS'
E>       -----------------------------------
E> ERROR: package installation failed
```

Would you help me?

I managed to install the old version, but I would like to install the new version to use all the function.

**Comment by spokswinski** [comment]
your "glue" package that is a dependency is not up-to-date. Because this is not installable from CRAN, you will have to update it manually. Based on recent loadings of this package on several computers, glue is probably not the only thing that needs updating. You may even have to update base R.

**Comment by karasinski88** [comment]
Thank you! it worked now.
