### ISSUE TITLE
Reverse dependency check of lidR 2.1.0

### ISSUE THREAD

**Issue by Jean-Romain** [tiagodc/TreeLS#5]
Hi Tiago,

I ran a reverse dependency check on `TreeLS v1.0` with the new version of `lidR v2.1.0`.  In ` tlsNormalize` documentation the example now have a warning.

```r
tls = tlsNormalize(tls)
#> Warning message:
#> There were 3 degenerated ground points. Some X Y coordinates were repeated but with different Z coordinates. min Z were retained. 
```

This is because `grid_terrain` now checks for degenerated ground points. See [#264](https://github.com/Jean-Romain/lidR/issues/264). R CMD check does not complain about that but I'm pretty sure that CRAN will.

**Comment by tiagodc** [comment]
Thanks, Jean!

I'll fix the function before the next release.

Best regards

**Comment by Jean-Romain** [comment]
This one is not a problem on CRAN actually. I'm just giving you the information
