### ISSUE TITLE
Trouble installing on Windows 10. R 4.3.0

### ISSUE THREAD

**Issue by mayhaw** [tiagodc/TreeLS#54]
If I enter:
`devtools::install_github('tiagodc/TreeLS'))`
I get in the console:
(....several thousand lines of stuff that ends with:)
```
`make: *** [C:/PROGRA~1/R/R-43~1.0/etc/x64/Makeconf:272: algorithms.o] Error 1    
ERROR: compilation failed for package 'TreeLS'
 ─  removing 'C:/Users/.../AppData/Local/Temp/RtmpAlb73w/Rinst12a0248379a2/TreeLS'
          -----------------------------------    
ERROR: package installation failed Error: Failed to install 'TreeLS' from GitHub:   
! System command 'Rcmd.exe' failed
`
```
Also this is the first time I've ever seen bold text in the console. Weird.
 
 ALSO:
If I enter:
`install.packages("https://cran.r-project.org/src/contrib/Archive/TreeLS/TreeLS_2.0.2.tar.gz")`
I Get in the console:
```
(....a several thousand lines of stuff that ends with:)
make: *** [C:/PROGRA~1/R/R-43~1.0/etc/x64/Makeconf:272: algorithms.o] Error 1
ERROR: compilation failed for package 'TreeLS'
* removing 'C:/Users/sabloszi/AppData/Local/R/win-library/4.3/TreeLS'
Warning in install.packages :
  installation of package ‘C:/Users/sabloszi/AppData/Local/Temp/RtmpQnjKyp/downloaded_packages/TreeLS_2.0.2.tar.gz’ had non-zero exit status
```

Of course, trying install.packages("TreeLS") doesn't work since it's not on CRAN anymore.

**Comment by mayhaw** [comment]
nope, still stuck and haven't come back to it but am meaning to get back to seeing if there are other options/help on the internet or somewhere

**Comment by plent** [comment]
Me too - from what I can tell, TreeLS isn't compatible with R v4, but I'm also unable to install/run it through R v3 because the dependencies rely on R v4? Would love to knw if there are plans to maintain/update the package.

**Comment by tiagodc** [comment]
I just updated the c++ compiler standard to match the one adopted by Rv4 and performed a fresh installation on windows under R 4.3 successfully. Just be sure you have an Rtools installed that matches your R version and you should be able to install TreeLS using `remotes::install_github('tiagodc/TreeLS')` without any problems.
