### ISSUE TITLE
Query Regarding the ShapeFit.Fork method

### ISSUE THREAD

**Issue by tomishninja** [tiagodc/TreeLS#56]
I was just wondering what type of a las file "shapeFit.forks" is designed to use.

Is it designed to work within another process (like "tlsInventory") or should I feed it the whole point cloud or should I be converting my point cloud into slices first? 

I am sorry if this isn't the right place to ask this. I understand the future is experimental and I am not expecting it to work flawlessly. I just want to make sure I am using it correctly.

**Comment by spono** [comment]
as you can see in this line of the tutorial
`inv = tlsInventory(tls, d_method=shapeFit(shape='circle', algorithm = 'irls'))`

`shapeFit/shapeFit.fork` is a method used within `tlsInventory`. Unfortunately it got stucked in the middle of the development process and it's "incomplete".

**Comment by tomishninja** [comment]
That makes sense, I did initially try to put it into the `tlsInventory` method but it quickly failed. I managed to get it to run on some normalized plots, but the results were not what I was expecting. Still I look forward to seeing it in action.
