### ISSUE TITLE
stemSegmentation function 

### ISSUE THREAD

**Issue by npuletti** [tiagodc/TreeLS#6]
Hello,
I'm trying to extract tree measures by _stemSegmentation(myTLSdata, sgmt.ransac.circle(tol = 0.001, n=5))_. Using this function recursively on more than 20 forest plots, I receive an error only for 1 plot:

Error in do.call(., what = rbind) : second argument must be a list

Why?

**Comment by tiagodc** [comment]
Hi @npuletti 

thanks for the feedback. I have an idea about where the issue might be, but I need to reproduce the error to confirm. Can you share with me the data set for which you got the error? Also I need some reproducible code - the script you used to generate _myTLSdata_.

Can you share those? If it's private, you can send me a link at tdc.florestal@gmail.com so I can have access to the data/script.

Cheers!

**Comment by npuletti** [comment]
Dear @tiagodc 

now the _Error in do.call_ seems to be fit. Probably it was due to old version of some dependencies.
Now I have another question for you and I will open a new issue and share my code and data.

Cheers. N
