### ISSUE TITLE
Hello，I have a  suggestions and references about TLS

### ISSUE THREAD

**Issue by LiuQW-YNnormal** [tiagodc/TreeLS#9]
Hello,  I saw the package you released TreeLS 1.0  , I want to ask how I can update the TreeLS on CRAN,   emmmmmmm, then  I saw the  project is ongoing , Could the function of single tree segmentation be added? I  saw a function about segmentation in "Segmenting tree crowns from terrestrial and mobile LiDAR data by exploring ecological theories-Tao". Maybe it could help you.

**Comment by tiagodc** [comment]
Hi, thanks for the tip!

I am slowly retaking the development of TreeLS, as it hasn't been updated for some time and many things are now broken. The next version will add some new features but full tree segmentation is not there yet. Sometime in the future I want to implement some QSM methods and other functions related to ecological features. Pull requests and references to software _libs_ that perform those tasks are always appreciated though. Cheers!
